# Generated by Django 5.0.6 on 2024-05-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Авторы')),
                ('Stat', models.CharField(max_length=100, verbose_name='Статья')),
                ('full_text', models.TextField(max_length=300, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
